export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_SET_REDIRECT = 'AUTH_SET_REDIRECT';

export const USER_FETCH_DATA = 'USER_FETCH_DATA';
export const USER_FETCH_ALL_DATA = 'USER_FETCH_ALL_DATA';
export const USER_FETCH_DATA_FAIL = 'USER_FETCH_DATA_FAIL';
export const USER_FETCH_DATA_START = 'USER_FETCH_DATA_START';
export const USER_FETCH_DATA_END = 'USER_FETCH_DATA_END';

export const FRIENDS_FETCH_REQUESTS = 'FRIENDS_FETCH_REQUESTS';
export const FRIENDS_ADD = 'FRIENDS_ADD';
export const FRIENDS_DELETE = 'FRIENDS_DELETE';
export const FRIENDS_CONFIRM = 'FRIENDS_CONFIRM';
export const FRIENDS_FAIL = 'FRIENDS_FAIL';

export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';

export const ROOM_ALL = 'ROOM_ALL';
export const ROOM_CREATE = 'ROOM_CREATE';
export const ROOM_JOIN = 'ROOM_JOIN';
export const ROOM_LEAVE = 'ROOM_LEAVE';
export const ROOM_ERROR = 'ROOM_ERROR';
export const ROOM_DELETE = 'ROOM_DELETE';
export const ROOM_DATA = 'ROOM_DATA';
export const ROOM_START = 'ROOM_START';
export const ROOM_GRAPH = 'ROOM_GRAPH';
export const ROOM_GRAPH_CHANGE = 'ROOM_GRAPH_CHANGE';
export const ROOM_END = 'ROOM_END';