export const INTERNAL_NOTIFICATIONS_ADD = 'INTERNAL_NOTIFICATIONS_ADD';
export const INTERNAL_NOTIFICATIONS_REMOVE = 'INTERNAL_NOTIFICATIONS_REMOVE';

export const AUTH_INITIATE = 'AUTH_INITIATE';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_UPDATE_CREDENTIALS = 'AUTH_UPDATE_CREDENTIALS';
export const AUTH_CLEAR_CREDENTIALS = 'AUTH_CLEAR_CREDENTIALS';
export const AUTH_REDIRECT = 'AUTH_REDIRECT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';

export const USER_FETCH_DATA = 'USER_FETCH_DATA';
export const USER_FETCH_HISTORY = 'USER_FETCH_HISTORY';
export const USER_FETCH_DATA_FAIL = 'USER_FETCH_DATA_FAIL';
export const USER_FETCH_DATA_START = 'USER_FETCH_DATA_START';
export const USER_FETCH_DATA_END = 'USER_FETCH_DATA_END';

export const FRIENDS_FETCH_REQUESTS = 'FRIENDS_FETCH_REQUESTS';
export const FRIENDS_ADD = 'FRIENDS_ADD';
export const FRIENDS_DELETE = 'FRIENDS_DELETE';
export const FRIENDS_CONFIRM = 'FRIENDS_CONFIRM';
export const FRIENDS_FAIL = 'FRIENDS_FAIL';

export const ROOM_ALL = 'ROOM_ALL';
export const ROOM_CREATE = 'ROOM_CREATE';
export const ROOM_JOIN = 'ROOM_JOIN';
export const ROOM_LEAVE = 'ROOM_LEAVE';
export const ROOM_ERROR = 'ROOM_ERROR';
export const ROOM_DELETE = 'ROOM_DELETE';
export const ROOM_DATA = 'ROOM_DATA';
export const ROOM_START = 'ROOM_START';
export const ROOM_GRAPH = 'ROOM_GRAPH';
export const ROOM_GRAPH_CHANGE = 'ROOM_GRAPH_CHANGE';
export const ROOM_END = 'ROOM_END';